import type { ContextDefinition } from "jsonld";

export const JSONLD_CONTEXT: ContextDefinition = {
  "@context": "https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context.jsonld",
};
export const PAGE_SIZE = 10;
export const PAGE = 0;
export const DEFAULT_LAT = 10.772;
export const DEFAULT_LNG = 106.667;
export const BUILDING_TYPES = [
  { label: "Apartments", value: "APARTMENTS" },
  { label: "Bakehouse", value: "BAKEHOUSE" },
  { label: "Barn", value: "BARN" },
  { label: "Bridge", value: "BRIDGE" },
  { label: "Bungalow", value: "BUNGALOW" },
  { label: "Bunker", value: "BUNKER" },
  { label: "Cathedral", value: "CATHEDRAL" },
  { label: "Cabin", value: "CABIN" },
  { label: "Carport", value: "CARPORT" },
  { label: "Cemetery", value: "CEMETERY" },
  { label: "Chapel", value: "CHAPEL" },
  { label: "Church", value: "CHURCH" },
  { label: "Civic", value: "CIVIC" },
  { label: "Commercial", value: "COMMERCIAL" },
  { label: "Conservatory", value: "CONSERVATORY" },
  { label: "Construction", value: "CONSTRUCTION" },
  { label: "Cowshed", value: "COWSHED" },
  { label: "Detached", value: "DETACHED" },
  { label: "Digester", value: "DIGESTER" },
  { label: "Dormitory", value: "DORMITORY" },
  { label: "Farm", value: "FARM" },
  { label: "Farm Auxiliary", value: "FARM_AUXILIARY" },
  { label: "Garage", value: "GARAGE" },
  { label: "Garages", value: "GARAGES" },
  { label: "Garbage Shed", value: "GARBAGE_SHED" },
  { label: "Grandstand", value: "GRANDSTAND" },
  { label: "Greenhouse", value: "GREENHOUSE" },
  { label: "Hangar", value: "HANGAR" },
  { label: "Hospital", value: "HOSPITAL" },
  { label: "Hotel", value: "HOTEL" },
  { label: "House", value: "HOUSE" },
  { label: "Houseboat", value: "HOUSEBOAT" },
  { label: "Hut", value: "HUT" },
  { label: "Industrial", value: "INDUSTRIAL" },
  { label: "Kindergarten", value: "KINDERGARTEN" },
  { label: "Kiosk", value: "KIOSK" },
  { label: "Mosque", value: "MOSQUE" },
  { label: "Office", value: "OFFICE" },
  { label: "Parking", value: "PARKING" },
  { label: "Pavilion", value: "PAVILION" },
  { label: "Public", value: "PUBLIC" },
  { label: "Residential", value: "RESIDENTIAL" },
  { label: "Retail", value: "RETAIL" },
  { label: "Riding Hall", value: "RIDING_HALL" },
  { label: "Roof", value: "ROOF" },
  { label: "Ruins", value: "RUINS" },
  { label: "School", value: "SCHOOL" },
  { label: "Service", value: "SERVICE" },
  { label: "Shed", value: "SHED" },
  { label: "Shrine", value: "SHRINE" },
  { label: "Stable", value: "STABLE" },
  { label: "Stadium", value: "STADIUM" },
  { label: "Static Caravan", value: "STATIC_CARAVAN" },
  { label: "Sty", value: "STY" },
  { label: "Synagogue", value: "SYNAGOGUE" },
  { label: "Temple", value: "TEMPLE" },
  { label: "Terrace", value: "TERRACE" },
  { label: "Train Station", value: "TRAIN_STATION" },
  { label: "Transformer Tower", value: "TRANSFORMER_TOWER" },
  { label: "Transportation", value: "TRANSPORTATION" },
  { label: "University", value: "UNIVERSITY" },
  { label: "Warehouse", value: "WAREHOUSE" },
  { label: "Water Tower", value: "WATER_TOWER" },
];

export const WEEK_DAYS = [
  "monday",
  "tuesday",
  "wednesday",
  "thursday",
  "friday",
  "saturday",
  "sunday",
];
