import type { ContextDefinition } from "jsonld";

export const JSONLD_CONTEXT: ContextDefinition = {
  "@context": "https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context.jsonld",
};
export const PAGE_SIZE = 10;
export const PAGE = 0;
export const DEFAULT_LAT = 10.772;
export const DEFAULT_LNG = 106.667;
export const BUILDING_TYPES = [
  { label: "apartments", value: "apartments" },
  { label: "bakehouse", value: "bakehouse" },
  { label: "barn", value: "barn" },
  { label: "bridge", value: "bridge" },
  { label: "bungalow", value: "bungalow" },
  { label: "bunker", value: "bunker" },
  { label: "cathedral", value: "cathedral" },
  { label: "cabin", value: "cabin" },
  { label: "carport", value: "carport" },
  { label: "cemetery", value: "cemetery" },
  { label: "chapel", value: "chapel" },
  { label: "church", value: "church" },
  { label: "civic", value: "civic" },
  { label: "commercial", value: "commercial" },
  { label: "conservatory", value: "conservatory" },
  { label: "construction", value: "construction" },
  { label: "cowshed", value: "cowshed" },
  { label: "detached", value: "detached" },
  { label: "digester", value: "digester" },
  { label: "dormitory", value: "dormitory" },
  { label: "farm", value: "farm" },
  { label: "farm_auxiliary", value: "farm_auxiliary" },
  { label: "garage", value: "garage" },
  { label: "garages", value: "garages" },
  { label: "garbage_shed", value: "garbage_shed" },
  { label: "grandstand", value: "grandstand" },
  { label: "greenhouse", value: "greenhouse" },
  { label: "hangar", value: "hangar" },
  { label: "hospital", value: "hospital" },
  { label: "hotel", value: "hotel" },
  { label: "house", value: "house" },
  { label: "houseboat", value: "houseboat" },
  { label: "hut", value: "hut" },
  { label: "industrial", value: "industrial" },
  { label: "kindergarten", value: "kindergarten" },
  { label: "kiosk", value: "kiosk" },
  { label: "mosque", value: "mosque" },
  { label: "office", value: "office" },
  { label: "parking", value: "parking" },
  { label: "pavilion", value: "pavilion" },
  { label: "public", value: "public" },
  { label: "residential", value: "residential" },
  { label: "retail", value: "retail" },
  { label: "riding_hall", value: "riding_hall" },
  { label: "roof", value: "roof" },
  { label: "ruins", value: "ruins" },
  { label: "school", value: "school" },
  { label: "service", value: "service" },
  { label: "shed", value: "shed" },
  { label: "shrine", value: "shrine" },
  { label: "stable", value: "stable" },
  { label: "stadium", value: "stadium" },
  { label: "static_caravan", value: "static_caravan" },
  { label: "sty", value: "sty" },
  { label: "synagogue", value: "synagogue" },
  { label: "temple", value: "temple" },
  { label: "terrace", value: "terrace" },
  { label: "train_station", value: "train_station" },
  { label: "transformer_tower", value: "transformer_tower" },
  { label: "transportation", value: "transportation" },
  { label: "university", value: "university" },
  { label: "warehouse", value: "warehouse" },
  { label: "water_tower", value: "water_tower" },
] as const;
export const WEEK_DAYS = [
  "monday",
  "tuesday",
  "wednesday",
  "thursday",
  "friday",
  "saturday",
  "sunday",
];
